name: Testing and Linting Golang Code
run-name: Golang Tests

env:
  DOCKER_BUILDKIT: 1

on:
  push:
    branches:
      - master
      - dev

  pull_request:
    branches:
      - dev

jobs:

  Install-Go-Packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Golang Code
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.7

      - name: Install packages
        run: go install

      - name: Build your go code
        run: go build

  Test-Go-Code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Golang Code
        uses: actions/checkout@v4

      - name: Install postgres
        run: sudo apt install postgresql

      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Connect to PostgreSQL and run query
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB_NAME }}
        run: |
          psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER -d $POSTGRES_DB -c "SELECT version();"

      - name: Test Code
        run: go test accounts


