name: Testing and Linting Golang Code
run-name: Golang Tests

env:
  DOCKER_BUILDKIT: 1

on:
  push:
    branches:
      - master
      - dev

  pull_request:
    branches:
      - dev

jobs:

  Install-Go-Packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Golang Code
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.7

      - name: Install packages
        run: go install

      - name: Build your go code
        run: go build

  Test-Go-Code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Golang Code
        uses: actions/checkout@v4

      - name: Install postgres
        run: sudo apt-get install postgresql

      - name: Start PostgreSQL Service
        run: sudo systemctl start postgresql

      - name: Install PostgreSQL client
        run: sudo apt-get install -y postgresql-client

      - name: Check PostgreSQL Service Status
        run: sudo systemctl status postgresql

      - name: Verify PostgreSQL Listening Ports
        run: sudo ss -tln

      - name: Connect to PostgreSQL and run query
        env:
          POSTGRES_USER: prime
          POSTGRES_PASSWORD: belindat2014
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: test_luxury
        run: |
          psql -h localhost -p 5432 -U prime -d test_luxury -W -c "SELECT version();"

      - name: Confirm
        run: "Successfult initialized database"

      - name: Test Code
        run: go test accounts


