name: Testing and Linting Golang Code
run-name: Golang Tests
on:
  - "push"

jobs:
  Install-Go-Packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Golang Code
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.7

      - name: Install packages
        run: go install

      - name: Build your go code
        run: go build

  Test-Go-Code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Golang Code
        uses: actions/checkout@v4

      # Set up Docker environment
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Pull PostgreSQL image from Docker Hub
      - name: Pull PostgreSQL image
        run: docker pull postgres:latest

      # Build and run PostgreSQL container with environment variables
      - name: Run PostgreSQL container
        run: |
          docker run -d \
            -e POSTGRES_USER=prime \
            -e POSTGRES_PASSWORD=belindat2014 \
            -e POSTGRES_DB=luxury \
            -p 5433:5433 \
            --name my_postgres_container \
            postgres:latest

      - name: Test Code
        run: go test
