name: Testing and Linting Golang Code
run-name: Golang Tests

env:
  DOCKER_BUILDKIT: 1

on:
  push:
    branches:
      - master
      - dev

  pull_request:
    branches:
      - dev
    branches-ignore:
      - dev

jobs:
  db:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DBNAME }}

  Install-Go-Packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Golang Code
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.7

      - name: Install packages
        run: go install

      - name: Build your go code
        run: go build

  Test-Go-Code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Golang Code
        uses: actions/checkout@v4

      - name: Run go code
        run: go run main.go

      - name: Test Code
        run: go test accounts
